apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: automation
    app.kubernetes.io/component: automation
    app.kubernetes.io/instance: automation
    version: v1
  name: automation
  namespace: quay
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: automation
      deployment: automation
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: automation
        deployment: automation
        version: v1
    spec:
      containers:
      - env:
        - name: VERIFY_TLS
          value: "0"
        image: quay.io/rhn_support_milang/quay-automation:v0.1.1
        imagePullPolicy: Always
        name: automation
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: automation
      serviceAccountName: automation
      terminationGracePeriodSeconds: 3
