apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: automation-edit
  namespace: quay
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: automation
  namespace: quay
